### ISSUE TITLE
CBaseMonster::IgnoreConditions

### ISSUE THREAD

**Issue by fnky** [baso88/SC_AngelScript#15]
Needs to be override-able in custom monster entities as well.

**Comment by fnky** [comment]
Sniper noted that it was added, but did not specify whether it was made override-able.

**Comment by fnky** [comment]
A baseclass version exists, but no override exists. Needs an override in `CBaseCustomMonsterEntity`.

**Comment by baso88** [comment]
The fix for this issue will be included in the next update (5.13). Closing.
