### ISSUE TITLE
CEngine is const, has configuration variables

### ISSUE THREAD

**Issue by fnky** [baso88/SC_AngelScript#20]
[`CEngine`](https://baso88.github.io/SC_AngelScript/docs/CEngine.htm) has only a const global instance, but has configuration variables used to instruct the engine to perform certain tasks. It should be made non-const, with non-configuration variables made const.

**Comment by fnky** [comment]
See this gist for an example on fixing this: [RegisterSCScriptEngine.as](https://gist.github.com/fnky/2d155a0c5b2ea38a550828d06da0762f)

`CEngine` marked non-const, readonly members marked const.

**Comment by baso88** [comment]
Selected variables were made non-const. This change will be included in the next update (5.13). Closing.
