### ISSUE TITLE
Add a way to get the material type of a texture

### ISSUE THREAD

**Issue by fnky** [baso88/SC_AngelScript#24]
There should be a way to get the material type of a texture. This would include an enum containing types and a method to retrieve the type of any texture.

**Comment by baso88** [comment]
Added CASSoundEngine::FindMaterialType() function that can be used to get the material type of a texture.
Enum containing all available material types is already exposed (see [TextureType](https://baso88.github.io/SC_AngelScript/docs/TextureType.htm) enum).

This change will be included in the next update (5.13). Closing.
