### ISSUE TITLE
BaseMonster::ISoundMask has incorrect documentation

### ISSUE THREAD

**Issue by fnky** [baso88/SC_AngelScript#25]
The documentation for `BaseMonster::ISoundMask` states the following:

> Calls the base class implementation of RunAI

This should be:

> Calls the base class implementation of ISoundMask

**Comment by fnky** [comment]
Trivial to fix, not fixed in 5.05.

**Comment by baso88** [comment]
The fix for this issue will be included in the next update (5.13). Closing.
