### ISSUE TITLE
CEngineFuncs::LightStyle passes temporary string, expects map lifetime string

### ISSUE THREAD

**Issue by fnky** [baso88/SC_AngelScript#31]
`CEngineFuncs::LightStyle` passes a temporary string to the engine, which expects a string that lasts as long as the map does. `ALLOC_STRING` the value.

**Comment by fnky** [comment]
Code to fix this:

```cpp
void CASEngineFuncs::LightStyle( int style, const CString& szVal )
{
    g_engfuncs.pfnLightStyle( style, MAKE_STRING( ALLOC_STRING( cszVal.CStr() ) ) );
}
```

In `trunk/dlls/Angelscript/ScriptTypes/ASEngineFuncs.cpp`

**Comment by baso88** [comment]
Fix for this issue will be part of the upcoming SC update (5.11).
