### ISSUE TITLE
CEntityFuncs methods handle array incorrectly

### ISSUE THREAD

**Issue by fnky** [baso88/SC_AngelScript#34]
The [`CEntityFuncs`](https://baso88.github.io/SC_AngelScript/docs/CEntityFuncs.htm) methods`MonstersInSphere`, `EntitiesInBox`, `TargetsInBox`, `BrushEntsInBox` don't release the reference to the array that is passed in if the array type is invalid.

**Comment by baso88** [comment]
The fix for this issue will be included in the next update (5.13). Closing.
