### ISSUE TITLE
Custom entity support in plugins is non-functional

### ISSUE THREAD

**Issue by fnky** [baso88/SC_AngelScript#46]
5.0.7's changelog says this:
"Server plug-ins are now allowed to register custom entities."

While the access mask for those methods was changed, you forgot pretty much everything else.

Custom entities require headers to be included so script classes can inherit from them properly. You also didn't set the access mask for custom weapon functions so you can't register custom weapons.

You also didn't update the code to use the calling module to check for the class name that was passed in, so it always tries to find classes in the map module.

**Comment by baso88** [comment]
Fix for this issue will be part of the upcoming SC update (5.11).
