### ISSUE TITLE
[Request] On entity killed

### ISSUE THREAD

**Issue by stevefan1999-personal** [baso88/SC_AngelScript#77]
I want to hook the function when a monster is killed

**Comment by hzqst** [comment]
This is what you need :
https://github.com/DrAbcOfficial/asexthook#332-monsterkilled
https://github.com/DrAbcOfficial/asexthook#334-breakablekilled

**Comment by stevefan1999-personal** [comment]
@hzqst long time no see haha, but thanks

**Comment by R4to0** [comment]
Forgot this issue ticket existed lol. MonsterTakeDamage and MonsterKilled hooks are exposed natively in the game for the next update, only god knows when it will be...
